# Per-skill XP/level progression: each annotated feature accrues XP and levels
# on its own, with perk-gated cosmetic particle effects. See profile/events/ui.
from .events import (
    LevelUp,
    award,
    award_inference,
    award_training,
    last_gain,
    peek_pending,
    pop_level_up,
    recent_features,
    time_since_feature,
    time_since_last_award,
)
from . import particles
from .perks import PERK_TIERS, PerkTier, next_perk_for_level, perk_for_level
from .profile import (
    LEVEL_CAP,
    PROFILE_PATH,
    Profile,
    get_profile,
    level_for_xp,
    mark_dirty,
    maybe_save,
    xp_into_level,
)
from .background import (
    frame as background_frame,
    pulse as background_pulse,
    stroke as background_stroke,
)
from .ui import (
    BIG_FONT_PX,
    EFFECT_TOGGLES,
    PERK_UNLOCK_LEVEL,
    big_font_path,
    draw_particles,
    emit_box_burst,
    emit_brush_trail,
    is_cosmetics_debug_open,
    is_skills_open,
    render_cosmetics_debug,
    render_level_up,
    render_skills_panel,
    render_xp_hud,
    set_big_font,
    set_panel_icon,
    tick_particles,
    toggle_cosmetics_debug,
    toggle_skills_panel,
)
from .cosmetics import background_choices, equip_background, equipped_background_id

__all__ = [
    "LevelUp",
    "award",
    "award_inference",
    "award_training",
    "last_gain",
    "peek_pending",
    "pop_level_up",
    "recent_features",
    "time_since_feature",
    "time_since_last_award",
    "particles",
    "PERK_TIERS",
    "PerkTier",
    "next_perk_for_level",
    "perk_for_level",
    "LEVEL_CAP",
    "PROFILE_PATH",
    "Profile",
    "get_profile",
    "level_for_xp",
    "mark_dirty",
    "maybe_save",
    "xp_into_level",
    "BIG_FONT_PX",
    "EFFECT_TOGGLES",
    "PERK_UNLOCK_LEVEL",
    "background_frame",
    "background_pulse",
    "background_stroke",
    "big_font_path",
    "draw_particles",
    "emit_box_burst",
    "emit_brush_trail",
    "is_cosmetics_debug_open",
    "is_skills_open",
    "render_cosmetics_debug",
    "render_level_up",
    "render_skills_panel",
    "render_xp_hud",
    "set_big_font",
    "set_panel_icon",
    "tick_particles",
    "toggle_cosmetics_debug",
    "toggle_skills_panel",
    "background_choices",
    "equip_background",
    "equipped_background_id",
]
