# Per-skill XP/level progression: each annotated feature accrues XP and levels
# on its own, with perk-gated cosmetic particle effects. See profile/events/ui.
from .events import (
    LevelUp,
    award,
    last_gain,
    peek_pending,
    pop_level_up,
    recent_features,
    time_since_feature,
    time_since_last_award,
)
from . import particles
from .perks import PERK_TIERS, PerkTier, next_perk_for_level, perk_for_level
from .profile import (
    LEVEL_CAP,
    PROFILE_PATH,
    Profile,
    get_profile,
    level_for_xp,
    mark_dirty,
    maybe_save,
    xp_into_level,
)
from .ui import (
    BIG_FONT_PX,
    PERK_UNLOCK_LEVEL,
    big_font_path,
    draw_particles,
    emit_box_burst,
    emit_brush_trail,
    is_panel_open,
    render_level_up,
    render_profile_panel,
    render_xp_hud,
    set_big_font,
    set_panel_icon,
    tick_particles,
    toggle_panel,
)

__all__ = [
    "LevelUp",
    "award",
    "last_gain",
    "peek_pending",
    "pop_level_up",
    "recent_features",
    "time_since_feature",
    "time_since_last_award",
    "particles",
    "PERK_TIERS",
    "PerkTier",
    "next_perk_for_level",
    "perk_for_level",
    "LEVEL_CAP",
    "PROFILE_PATH",
    "Profile",
    "get_profile",
    "level_for_xp",
    "mark_dirty",
    "maybe_save",
    "xp_into_level",
    "BIG_FONT_PX",
    "PERK_UNLOCK_LEVEL",
    "big_font_path",
    "draw_particles",
    "emit_box_burst",
    "emit_brush_trail",
    "is_panel_open",
    "render_level_up",
    "render_profile_panel",
    "render_xp_hud",
    "set_big_font",
    "set_panel_icon",
    "tick_particles",
    "toggle_panel",
]
